import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# 1. Load the scatter data
# Data is generated by run_scatter_experiment in experiment.cpp
df = pd.read_csv('../results/scatter_results.csv')

# Target instances from your main.cpp list
targets = ['sko81', 'tai64c']

for inst in targets:
    # Filter data for the specific instance
    data = df[df['Instance'] == inst]
    
    if data.empty:
        continue

    plt.figure(figsize=(10, 8))
    sns.set_style("whitegrid")

    # Theme: Greedy (G) = Crosses (X), Steepest (S) = Circles (o)
    markers = {"G": "X", "S": "o"}
    colors = {"G": "royalblue", "S": "crimson"}

    # Create the scatter plot
    sns.scatterplot(
        data=data, 
        x='InitCost', 
        y='FinalCost', 
        hue='Algo', 
        style='Algo', 
        markers=markers,
        palette=colors,
        alpha=0.7,
        s=100,         # Slightly larger markers for better visibility
        edgecolor='w'
    )

    # Calculate Pearson Correlation
    stats_text = f"Instance: {inst}\n"
    for algo in ['G', 'S']:
        subset = data[data['Algo'] == algo]
        if len(subset) > 1:
            r, _ = pearsonr(subset['InitCost'], subset['FinalCost'])
            stats_text += f"{algo}: $r = {r:.3f}$\n"

    # Annotate the plot
    plt.text(0.05, 0.95, stats_text, transform=plt.gca().transAxes, 
             fontsize=12, verticalalignment='top', 
             bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    # --- AXIS OPTIMIZATION ---
    # By removing the identity line and not setting manual limits, 
    # Matplotlib will automatically "zoom" to the data bounds.
    # To ensure it's tight, we can explicitly set margins to a small value (e.g., 2%)
    plt.margins(x=0.02, y=0.02)

    plt.title(f'Fitness Landscape: Initial vs. Final Cost ({inst})', fontsize=16)
    plt.xlabel('Initial Cost', fontsize=12)
    plt.ylabel('Final Cost', fontsize=12)
    plt.legend(title='Algorithm', loc='best')
    plt.tight_layout()

    # Save output files
    plt.savefig(f'../results/scatter_{inst}_zoom.png', dpi=300)
    plt.close()